### PR TITLE
bad/good instead of preferred/not preferred

### PR DESCRIPTION
**Pull request by ismaelga**
I think it reads better if we use bad/good instead of preferred/not preferred.

At other style guides I've seen they also use bad/good so that might be the preferred way

### CODE REVIEW

**Comment by whatyouhide** [comment]
I'm in favour of this one :+1: What do you think @knewter and @niftyn8?

**Comment by knewter** [comment]
I was leaving it for someone else to merge since I had no real opinion :)

On Mon, Feb 2, 2015 at 3:30 AM, Andrea Leopardi <notifications@github.com>
wrote:

> I'm in favour of this one [image: :+1:] What do you think @knewter
> <https://github.com/knewter> and @niftyn8 <https://github.com/niftyn8>?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/niftyn8/elixir_style_guide/pull/30#issuecomment-72427521>
> .
>



-- 
*Josh Adams*
CTO | isotope|eleven <http://www.isotope11.com>
[cell] (205) 215-3957
[work] (877) 476-8671 x201

**Comment by niftyn8** [comment]
I prefer preferred personally, mostly because in nearly every language I've worked in and looked at a style guide there's exceptions to the rules... but I don't have much of a dog in the fight. 

Do what thou wilt. Would rather someone else merge though or at least get maybe one or two more people in enthusiastic agreement before merging...

**Comment by asaaki** [comment]
I would stick with `preferred/not preferred` as it sounds less judgmental (to me).
And also agree with @niftyn8 that there can and will be always exceptions to some rules.

IMHO a style guide should not enforce but … guide. :wink:

As we're already talking about wording here: What about _recommendations_ instead of _rules_?

**Comment by niftyn8** [comment]
> What about recommendations instead of rules?

Like it, personally.

**Comment by ismaelga** [comment]
Well, my problem with preferred/not preferred is not the meaning of it. I simply feel it's way easier to read "good" vs "bad" instead of "preferred" vs  "not preferred".

To not enforce people you can just state at the start of the guide that these are only recommendations and not rules. So this way, "bad" kind of means "not preferred".

IMHO any alternative that's not simply using negation of preferred (which I think is the cause for the struggle it causes into my eyes when reading) is better.

"preferred" vs "not recommended"/"inadvisable" might be a good alternative if you really don't wan't it to sound too imposing.

**Comment by niftyn8** [comment]
> IMHO any alternative that's not simply using negation of preferred (which I think is the cause for the struggle it causes into my eyes when reading) is better.

> "preferred" vs "not recommended"/"inadvisable" might be a good alternative if you really don't wan't it to sound too imposing.

You make excellent points. Thanks much for the work. I'm going to close this *only* because at this point it's stale and I would rather go in the direction of preferred vs inadvisable (or similar). I'll open a new PR to do that later if no one else does first. @ismaelga if you feel slighted by me closing this please feel free to open back up and get it back up to date.

Thanks again!

**Pull request closed without merging**
