### PR TITLE
Parentheses with anonymous function arguments

### PR DESCRIPTION
**Pull request by jeffcole**
Hi there!

I noticed that the style guide has a preference for parentheses when there are arguments to named functions, but doesn't mention anonymous functions. One might take the position that we should be consistent in our treatment of arguments to both types of functions, so this pull request makes that consistency explicit.

I included a concession (stating that no parentheses are OK) for the case that there is a single argument to an anonymous function, as most of the code I've seen allows for that style, perhaps for its expediency. 

I then updated a few of the examples in the guide to be consistent with this style.

Please let me know what you think! Thank you for this excellent resource!

### CODE REVIEW

**Comment by ericmj** [comment]
I think it's most common to always omit parenthesis around parameters for anonymous functions. It's the convention in all https://github.com/elixir-lang/ projects and most major open source projects I know of.

**Comment by jeffcole** [comment]
Hi @ericmj, thanks for the feedback! From searching around, I can't seem to find a consensus one way or the other. Check out [these](https://github.com/elixir-lang/plug/search?p=4&q=fn&utf8=%E2%9C%93) [examples](https://github.com/phoenixframework/phoenix/search?p=5&q=fn&utf8=%E2%9C%93).

I think we stand to gain from preferring consistency between named and anonymous functions. In my opinion, parentheses also make it easier to read and parse function calls that take an anonymous function as a parameter. For example, in the following, I feel more able to differentiate the start of the anonymous function when parentheses are used around its parameters:

```elixir
Enum.map_reduce([1, 2, 3], 0, fn x, acc -> {x * 2, x + acc} end)

Enum.map_reduce([1, 2, 3], 0, fn (x, acc) -> {x * 2, x + acc} end)
```

I do think allowing for omitting parenthesis when there is a single parameter is a good approach, as I've included in this pull request. What do folks think?

**Comment by ericmj** [comment]
The examples you linked with parenthesis are either from 2014 or from outside contributors, you will always be able to find inconsistencies because we don't enforce specific styles strongly. We prefer to try to merge PRs quickly instead of getting hung up on style changes. If you look through the repos you will find that the vast majority of anon functions do not use parenthesis.

For named functions we recommend using parenthesis because it's easy to get conflicts otherwise. With anonymous functions the conflicts are practically non-existent. Because of that the parenthesis are just extra noise to me.

**Comment by jeffcole** [comment]
Thanks @ericmj! I'm closing due to this feedback.

**Pull request closed without merging**
