### PR TITLE
Added guideline for using :else as the catch-all in cond.

### PR DESCRIPTION
**Pull request by indiejames**

### CODE REVIEW

**Comment by whatyouhide** [comment]
I've seen `true` a lot more frequently than `:else` in `cond` statements. Can you point to somewhere `:else` is used instead?

**Comment by indiejames** [comment]
This is taken from the [Clojure style guide](https://github.com/bbatsov/clojure-style-guide) for `cond` in Clojure, and I think it makes a lot of sense. `:else` is explicit about the condition (choose this when all else fails), whereas `true` is not.

**Comment by whatyouhide** [comment]
@indiejames well, `true` is explicit in that it follows the `cond` philosophy (if an expression before `->` is true, the one after `->` is returned). IMO, `:else` feels a little hacky, since it's handled as a special case.

The [getting started guide](http://elixir-lang.org/getting-started/case-cond-and-if.html#cond) doesn't even introduce `:else` when it talks about `cond`.

**Comment by indiejames** [comment]
The getting started guide says this with respect to cond:

" Finally, note `cond` considers any value besides nil and false to be true"

`:else` is not a special case, it's simply equal to `true` (truthy). Any other non-nil, non-false value could be used, but `:else` reads well (to me and Clojure people, at least.). 

I suspect you will start to see people using other things, like `:default` that they think convey more meaning than just `true`. I'm simply suggesting heading that off so everyone uses the same thing.

**Comment by whatyouhide** [comment]
@indiejames well, my bad :smile: Yes, `:else` is an arbitrary truthy value so it's not handled as a special case. Sorry!

That said, I still stand by using `true` since it's the prince of the truthy values and, IMO, it conveys much more information than a random (well, not random, but still) atom like `:default` or `:else` or `:well_if_we_are_here_everything_else_was_false`.
That may be my personal opinion, but ignoring huge amounts of existing code which use `true` in favour of `:else` may not be the right choice. Maybe other people will start using other things like `:default` as you say, but a quick grep on the source of Elixir, Ecto, Plug and Phoenix shows no uses of `:else` in `cond` causes (`:Ag :else` in vim with ag.vim, I may be wrong!).

What do you think?

**Comment by indiejames** [comment]
I think the most important reason for guidelines is consistency, so it
probably is better to stick with what most people are using. Still, I can't
help but wonder if the use of `true ->` everywhere is just because no one
has thought to do it any other way (Elixir is still pretty young). And I DO
think `:else ->` reads better, like in the case of the `Dict` module, where
you have things like this:

    true ->
        false

**Comment by asaaki** [comment]
> That said, I still stand by using `true` since it's the prince of the truthy values […]

I like this statement.

As it seems that naming things is difficult (as always) I would stick with `true`, too.

----

After digging into Elixir's source code I was curious if the usage of `true` or `:else` would have any performance impact. Turns out: not much. (fractions of μs maybe; [gist with benchmark](https://gist.github.com/asaaki/bd140501aad80b27fa72))
So I don't mind at all, I almost never use `cond`.

**Comment by indiejames** [comment]
@asaaki Nice. Just for grins I ran your benchmark on my MBP:

*** &CondTest.cond_with_true/0 ***
114.9 sec   536M iterations   0.22 μs/op

*** &CondTest.cond_with_atom/0 ***
108.1 sec   536M iterations   0.21 μs/op

*** &CondTest.cond_with_truthy_evaluation/0 ***
110.0 sec   536M iterations   0.21 μs/op

:else FTW  :smiley:

**Comment by creeonix** [comment]
`:else` looks more convenient since in all other programming languages we commonly use `default` or `else`.

Tried the [same thing](https://gist.github.com/creeonix/ab7ac96458aac739bbf9) on my iMac. `:else` is sometimes faster for some reason.

**Comment by asaaki** [comment]
Keep in mind: this benchmark was just a oneshot, and should only prove that there is no real significant difference in using the atom `true` or any other atom. (Though my assumption was that there was a good shortcut for the `true` branch and should always perform better, in reality it wasn't.)
Also keep in mind that `true`, `false` and `nil` are atoms, too, just with special meanings within Elixir.
(`true === :true`)

Conclusion: There is no harm to change from `true` to `:else` or `:default` as it seems that any atom perform pretty well in average over time.

**Comment by knewter** [comment]
I am actually in favor of the use of :else because I think true reads less
well. However I also don't think it's widespread yet at all. Decisions,
decisions. I'd give this a tentative +1. I'll at least try to start using
it in my code and see how it feels.

**Comment by jordan0day** [comment]
I think this should actually be submitted to elixir as a change in the language itself. That is, add support for a "default" or "else" **keyword** for `cond`. Relying on `:else` being truthy-by-default just kind of feels like a neat trick, rather than an artifact of a well-designed language.

That said, I'm personally a fan of @whatyouhide's `:well_if_we_are_here_everything_else_was_false`.

**Comment by niftyn8** [comment]
FWIW, Clojure pulls the same exact trick and we've all been doing it for ages. It works really nicely... I've never seen a really crazy atom thrown in there that made it confusing (I usually see `:else` or `:otherwise`). The Ruby community also takes advantage of the names of truthy values for adding clarity all the time.

I also don't understand the value of adding a keyword to the language... Would really over-complicate `cond` with little value.

Also in terms of whether or not it gets into the style guide... I learn towards the side of preferring good *style* in a style guide to exactly what seems to be happening in the community A) Because no one ever actually gets hard data to *show* that's what the community is actually doing more often than not and B) It's a guide for good style... If there's a style that's good it should be promoted IMO... Especially in such a young language with a small community.

That said, as per usual, I'll leave it up to others who are contributors and write more Elixir than I do... Ignore the Lisper ;)

**Comment by asaaki** [comment]
`:if_everything_else_is_false_then_this_seems_to_be_the_ultimate_truth` :wink:

**Comment by creeonix** [comment]
> I also don't understand the value of adding a keyword to the language... Would really over-complicate cond with little value.

the real value is readability and nothing `:else` ;)

**Comment by niftyn8** [comment]
Sure... Just don't understand what about a keyword is more or less readable than a symbol.

**Comment by jtmoulia** [comment]
Coming from Erlang, the [`if`](http://www.erlang.org/doc/reference_manual/expressions.html#id78310) statement is analogous to `cond`, and uses `true` for the default expression.

**Comment by niftyn8** [comment]
How do you all feel about changing this to a note that it's an option? Want to close out the current PRs one way or the other and move these conversations forward.

FWIW I don't think an argument like "this is more readable, no *this* is more readable" is going to go anywhere.

**Comment by knewter** [comment]
:+1:

**Comment by asaaki** [comment]
:+1:

**Comment by indiejames** [comment]
:+1:

**Comment by Gazler** [comment]
To move this forward, I have created a pull-request that notes that it is an option. https://github.com/niftyn8/elixir_style_guide/pull/44

**Comment by niftyn8** [comment]
Thanks! Merged!

**Pull request closed without merging**
