### PR TITLE
rename camelcase to pascalcase

### PR DESCRIPTION
**Pull request by kholbekj**
Too nitty gritty? :smile_cat:

### CODE REVIEW

**Comment by MEHColeman** [comment]
That's interesting, I just looked it up on Wikipedia, because I'd not heard of PascalCase. The quick summary: Microsoft calls only words starting with a lower case letter camelCase; words starting with a capital letter are called PascalCase.
The commonly held definition of camelCase, though, seems to cover words starting with either a capital or a lower case letter.

IMHO what this change adds in precision, it takes away in clarity, but maybe that's just me, and PascalCase isn't as obscure as I think it is ¯\_(ツ)_/¯

**Comment by kholbekj** [comment]
The english wikipedia page is misleading IMO. It's not a microsoft invention, or a practise to them only. 
If it's a generally unknown difference, I'm not pushy about merging, to me it always makes me twitch to see "CamelCase", as the two versions really do need different names.

But again, could be I'm an oddball in even stopping to think.

**Comment by asaaki** [comment]
I would suggest to add a link to an explanation of such terms, as it is not always clear to everybody.

_PascalCase_ might be correct and more accurate, but I know a lot of people not knowing this term. They would probably refer to _camel case starting with a capital letter_.

**Comment by kholbekj** [comment]
Well, if it needs an explanation, it doesn't belong here. I'll bite my tongue at let is slide :)

**Pull request closed without merging**
