### PR TITLE
Specify how to indent the do: syntax in functions

### PR DESCRIPTION
**Pull request by whatyouhide**
I see this in most `elixir-lang/*` repositories, so I guess it makes sense to add it in the style guide :). Let me know what you think!

### CODE REVIEW

**Comment by asaaki** [comment]
Hm, I'd rather use the (more verbose)  `do … end` instead if the line is too long for a `do: …`.
So, I'm not sure if this is a good pattern at all.

But in case this is a good style, I support this proposal.

**Comment by whatyouhide** [comment]
@asaaki if the function is just a single clause, then I absolutely agree with you that this:

```elixir
def foo do
  :very_long_line
end
```

is better than 

```elixir
def foo,
  do: :very_long_line
```

However, it has happened quite a few times to me that you have a function with a bunch of single-line clauses and only one is a long line (but still a single line), and in those cases I love to do:

```elixir
def foo(1),
  do: 1
def foo(2),
  do: 2
def foo(3),
  do: :very_long_line
```

and this is a pattern that I've seen a few times in the wild. Describing it in the style guide seemed a little bit too complicated, that's why I was a little less specific :)

**Comment by asaaki** [comment]
Hm, I'm not afraid of mixing the oneliners and blocks. :sweat_smile: 

Just to be clear, your proposal seems to be totally fine.
Again I might just need to adapt and get used to it. (similar to _no indentation for multiline pipes_)

**Comment by whatyouhide** [comment]
@asaaki let's wait for feedback from others and see what they say then :+1: :)

**Comment by knewter** [comment]
I'm :+1: on it though I basically never use it.  I've seen it in the wild and it wasn't confusing.

**Comment by whatyouhide** [comment]
@knewter I tend to use it a lot because I can read multiple function clauses much better when they're very close to each other. Using `do...end` makes it harder for me as the function clauses look more "separated": with `do:`, it's obvious they're all clauses of the same function.

**Comment by doomspork** [comment]
I'm in @asaaki's camp on this one.   I typically use `do...end` if it extends beyond 80 as one line.  I don't mind mixing blocks and one liners though I do make an effect to keep the blocks towards the end.

I personally like having the `def` and `do` on the same line.

**Comment by adamzaninovich** [comment]
I agree with @asaaki and @doomspork. I would just use the multiline syntax in this case. I also have no problem mixing multiline and single line function definitions. Really though, if your one-liner is that long, it probably shouldn't be a one-liner.

I vastly prefer this:
```elixir
def foo(1), do: 1
def foo(2), do: 2
def foo(3) do
  :very_long_line
end
```

over this:
```elixir
def foo(1),
  do: 1
def foo(2),
  do: 2
def foo(3),
  do: :very_long_line
```

To me, it's a code smell that the line is that long in the first place. Then, the perfectly good one-line syntax of the first two legitimate one-liners are basically being infected by the third.

Probably even better would be (depending on the actual code):
```elixir
def foo(1), do: 1
def foo(2), do: 2
def foo(3) do
  :multiple
  :lines
end
```

**Comment by alxndr** [comment]
another :+1: agreeing with @asaaki @doomspork @adamzaninovich etc.

**Comment by notdevinclark** [comment]
I have to agree with @alxndr, @asaaki, @doomspork, and @adamzaninovich. We all want clean, easy to read code; hence this style guide's existence. 

If a single line is too long, there is a large chance that it is harder to read and would benefit from being broken up into multiple lines. Moving it below doesn't help readability, and may only save you only so many characters depending on the length of the function definition.

**Comment by eksperimental** [comment]
@adamzaninovich : the thing is the your example is different that what you see in real life code 
which is more like this:

```elixir
def foo(arg1, arg2, _arg3) when is_integer(arg1) and is_atom(arg2), do: arg1 + 1
def foo(arg1, _arg2, arg3) when is_integer(arg1), do: arg3
def foo(_, _, _) do
  :default_value
end
```

or

```elixir
def foo(arg1, arg2, _arg3) when is_integer(arg1) and is_atom(arg2) do
  arg1 + 1
end
def foo(arg1, _arg2, arg3) when is_integer(arg1) do
  arg3
end
def foo(_, _, _) do
  :default_value
end
```


@whatyouhide proposal I think suits better

```elixir
def foo(arg1, arg2, _arg3) when is_integer(arg1) and is_atom(arg2),
  do: arg1 + 1
def foo(arg1, _arg2, arg3), when is_integer(arg1),
  do: arg3
def foo(_, _, _),
  do: :default_value
```
I find this last one much easier to read, because i know where to look for the return value.
concise!

**Comment by adamzaninovich** [comment]
Really, if the lines of code are that short, this is probably better:
```elixir
def foo(arg1, arg2, _arg3) when is_integer(arg1) and is_atom(arg2), do: arg1 + 1
def foo(arg1, _arg2, arg3) when is_integer(arg1), do: arg3
def foo(_, _, _), do: :default_value
```

but I don't think anyone is arguing against that, as this proposal has to do with situations where the lines are long.

This might be a better real world example in the style of the proposal:
```elixir
def foo(arg1, arg2, _arg3) when is_integer(arg1) and is_atom(arg2),
  do: if length(arg1) > 0, do: arg2, else: :default_value
def foo(arg1, _arg2, arg3) when is_integer(arg1),
  do: arg3
def foo(_, _, _),
  do: :default_value
```

but I find the block syntax (with a bit of refactoring of the long line of code) to be much more readable:
```elixir
def foo(arg1, arg2, _arg3) when is_integer(arg1) and is_atom(arg2) do
  cond do
    length(arg1) > 0 -> arg2
    true -> :default_value
  end
end
def foo(arg1, _arg2, arg3) when is_integer(arg1), do: arg3
def foo(_, _, _), do :default_value
```

**Comment by eksperimental** [comment]
@adamzaninovich  the proposal is about long lines, not sort.
the proposal fits pretty much for your first example in your last message.

And I don't think it's about cases like your second example.
Maybe @whatyouhide should be more explicit, and mention "when it can be broken into two lines".

**Comment by niftyn8** [comment]
Bump, does anyone want to move forward on this one?

**Comment by asaaki** [comment]
I've used the proposed recommendation for some time and have to say that I actually like it pretty much now.

So, if there are no real objections I would say, we could give it a try.

**Comment by niftyn8** [comment]
I'm partial to this style as well... it's very similar to some things commonly done in a few other languages...

**Comment by niftyn8** [comment]
If I'm understanding everyone clearly in the past it sounds like most folks were in agreement... I'm going to merge from now and any dissenters feel free to bring it up again.

Thanks!

**Pull request merged**
