### PR TITLE
Don't put multiple function defs together

### PR DESCRIPTION
**Pull request by tallakt**
I think this is more like what you would find in elixir source code...

### CODE REVIEW

**Comment by mschae** [comment]
Yeah I am in favour of keeping it as suggested right now.

I personally had to adjust to multiple function definitions not being separated, but once I got used to it it made reading code easier because it shows right away "what belongs together".

**Comment by jtmoulia** [comment]
:+1: for what @Gazler said -- run together for single line clauses, split for multi-line clauses.

**Comment by niftyn8** [comment]
> :+1: for what @Gazler said -- run together for single line clauses, split for multi-line clauses.

Another :+1:.

Anyone want to open a PR for that?

**Comment by Gazler** [comment]
@niftyn8 @jtmoulia I have opened the pull request, would appreciate feedback on my addition of not mixing single-line and multi-line for more than one multi-line def.

**Pull request closed without merging**
